[colors.bright]
black = "#696969"
blue = "#007FFF"
cyan = "#00CCCC"
green = "#03C03C"
magenta = "#FF1493"
red = "#FF2400"
white = "#FFFAFA"
yellow = "#FDFF00"

[colors.cursor]
cursor = "#ff0017"

[colors.normal]
black = "#10100E"
blue = "#008df8"
cyan = "#20B2AA"
green = "#8ce00a"
magenta = "#9A4EAE"
red = "#C40233"
white = "#C6C6C4"
yellow = "#FFD700"

[colors.primary]
background = "#10100E"
foreground = "#ffffff"

[cursor]
blink_timeout = 0

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 12

[font.bold]
family = "Fira Code Nerd Font"
style = "Bold"

[font.italic]
family = "Fira Code Nerd Font"
style = "Italic"

[font.normal]
family = "Fira Code Nerd Font"
style = "Regular"

[window]
dynamic_padding = false
opacity = 0.85

[window.padding]
x = 2
y = 4

[env]
WINIT_HIDPI_FACTOR = "1"
WINIT_X11_SCALE_FACTOR = "1"
